
split_clients "${remote_addr}" $app_target {
    1% green_app;
    * green_app;
}

upstream blue_app {
    server blue_app:8000;
}

upstream green_app {
    server green_app:8000;
}

server {
    listen 80;
    location / {
        proxy_pass http://$app_target;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
