FROM python:3.10-alpine

WORKDIR /flask-app

COPY requirements.txt /flask-app

RUN pip3 install -r requirements.txt

COPY . /flask-app

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "board:create_app()"]
