input {
    beats {
        port => 5044
    }
}

filter {
  if [docker][container][name] == "logstash" {
    drop {}
  }

  grok {
    match => { "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\]\[%{LOGLEVEL:loglevel}\]%{SPACE}%{GREEDYDATA:logmessage}" }
    tag_on_failure => ["_grokparsefailure_app"]
  }

  if "_grokparsefailure_app" not in [tags] {
    date {
      match => [ "timestamp", "YYYY-MM-dd'T'HH:mm:ss,SSS" ]
      target => "@timestamp"
      remove_field => ["timestamp"]
    }
  }

  if "_grokparsefailure_app" in [tags] {
     drop {}
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "raw_logstash_test-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
